"""P3 synthetic contract checks; no trial files, layout coordinates or simulator."""
import ast
import asyncio
import copy
import inspect
import json
import math
import os
from pathlib import Path

import pytest

from programs.target_selection import select_target, selection_shortest_turn

ANGLE_CASES = [
    (350, 10, 20), (10, 350, -20), (355, 5, 10), (5, 355, -10), (-5, 5, 10),
    (170, -170, 20), (-170, 170, -20), (179, -179, 2), (-179, 179, -2), (175, -175, 10),
    (0, 0, 0), (0, 90, 90), (90, 0, -90), (0, -90, -90), (-90, 0, 90),
    (0, 180, 180), (180, 0, 180), (720, -900, 180), (45, 315, -90), (810, 450, 0),
]


def edge(name, a, b, length, one_way=False):
    return {"roadId": name, "fromNodeId": a, "toNodeId": b,
            "lengthCm": length, "oneWay": one_way}


def inputs_for_case(case):
    """Public-only fixture. Local observed road spans need not reveal transit roads."""
    s = case.get("current_s", 40)
    nprogress, fprogress = case.get("near_s", 10), case.get("far_s", 20)
    near, far = case.get("near_xy", (0, 1)), case.get("far_xy", (2, 0))
    geometry = {"roads": {"current": [{"s": 0, "x": 0, "z": -s / 100},
                                      {"s": 40, "x": 0, "z": (40 - s) / 100}]},
                "intervals": {"current": [[0, 40]]}}
    # Each target lies at the centre of an observed ten-centimetre span.
    for name, progress, point in [("near", nprogress, near), ("far", fprogress, far)]:
        geometry["roads"][name] = [{"s": progress - 5, "x": point[0] - .05, "z": point[1]},
                                    {"s": progress + 5, "x": point[0] + .05, "z": point[1]}]
        geometry["intervals"][name] = [[progress - 5, progress + 5]]
    return ([{"obj_id": "near", "x": near[0], "z": near[1], "confidence": .99},
             {"obj_id": "far", "x": far[0], "z": far[1], "confidence": .6}],
            {"edges": [edge("current", "S", "O", 40, case.get("current_one_way", False)),
                       edge("near", "N0", "N1", 100, case.get("near_one_way", False)),
                       edge("far", "F0", "F1", 100), *case["links"]]},
            {"roadId": "current", "roadProgressCm": s, "onRoad": True},
            {"rightCm": 0, "forwardCm": 0, "headingDeg": case.get("heading", 0), "tick": 0},
            geometry, case.get("k", .5))


# These are hand-solved topologies, not answers generated by a second Dijkstra.
# Expected tuple: near path, near initial turn, near cost, far path, far turn, far cost.
# k values are explicit SYNTHETIC algebra inputs, never runtime calibration.
SYNTHETIC_CASES = [
    {"name": "long_near_branch", "links": [edge("n", "O", "N0", 300), edge("f", "O", "F0", 200)],
     "expected": (310, 0, 310, 220, -90, 265), "proof": "Near=300+10; Far=200+20+0.5*90."},
    {"name": "current_and_target_partials", "current_s": 15, "near_s": 30, "far_s": 40,
     "links": [edge("n", "O", "N0", 400), edge("f", "O", "F0", 200)],
     "expected": (455, 0, 455, 265, -90, 310), "proof": "Current remainder=25; Near=25+400+30; Far=25+200+40+45."},
    {"name": "oneway_target_requires_loop", "near_one_way": True,
     "links": [edge("n", "O", "N1", 50, True), edge("return", "N1", "N0", 400, True), edge("f", "O", "F0", 200)],
     "expected": (460, 0, 460, 220, -90, 265), "proof": "N1 cannot enter near backwards:50+400+10; Far=200+20+45."},
    {"name": "oneway_current_partial", "current_s": 30, "current_one_way": True,
     "links": [edge("n", "O", "N0", 300), edge("f", "O", "F0", 200)],
     "expected": (320, 0, 320, 230, -90, 275), "proof": "Only forward current exit:10; Near=10+300+10; Far=10+200+20+45."},
    {"name": "weighted_multi_edge_alternative", "links": [edge("n-long", "O", "N0", 600),
     edge("nx", "O", "X", 200), edge("xn", "X", "N0", 130), edge("fy", "O", "Y", 100), edge("yf", "Y", "F0", 100)],
     "expected": (340, 0, 340, 220, -90, 265), "proof": "Near=min(600,200+130)+10; Far=100+100+20+45."},
    {"name": "target_reverse_partial", "near_s": 90,
     "links": [edge("n-left", "O", "N0", 400), edge("n-right", "O", "N1", 340), edge("f", "O", "F0", 200)],
     "expected": (350, 0, 350, 220, -90, 265), "proof": "Near=min(400+90,340+10)=350; Far=200+20+45."},
    {"name": "heading_favors_far", "heading": 90, "far_xy": (-2, 0),
     "links": [edge("n", "O", "N0", 350), edge("f", "O", "F0", 230)],
     "expected": (360, -90, 405, 250, 0, 250), "proof": "Near=350+10+45; Far=230+20+0."},
    {"name": "near_behind_far_forward", "near_xy": (0, -1), "far_xy": (0, 2), "k": 2,
     "links": [edge("n", "O", "N0", 110), edge("f", "O", "F0", 220)],
     "expected": (120, 180, 480, 240, 0, 240), "proof": "Near=110+10+2*180; Far=220+20."},
    {"name": "halfturn_tradeoff", "near_xy": (1, 0), "far_xy": (0, 2), "heading": 90, "k": 2,
     "links": [edge("n", "O", "N0", 120), edge("f", "O", "F0", 190)],
     "expected": (130, 180, 490, 210, -90, 390), "proof": "Near=120+10+2*180; Far=190+20+2*90."},
    {"name": "backward_start_partial_cheaper", "current_s": 10,
     "links": [edge("n", "O", "N0", 400), edge("f", "S", "F0", 210)],
     "expected": (440, 0, 440, 240, -90, 285), "proof": "Near=30+400+10; Far uses backward partial10+210+20+45."},
]


@pytest.mark.parametrize("current,target,expected", ANGLE_CASES)
def test_twenty_shortest_angles(current, target, expected):
    result = selection_shortest_turn(current, target)
    assert result == pytest.approx(expected)
    assert -180 < result <= 180


@pytest.mark.parametrize("case", SYNTHETIC_CASES, ids=lambda case: case["name"])
def test_ten_analytically_solved_euclidean_counterexamples(case):
    args = inputs_for_case(case)
    result = select_target(*args)
    near, far = result["candidates"]
    expected = case["expected"]
    assert [near["path_distance_cm"], near["turn_deg"], near["cost_cm"],
            far["path_distance_cm"], far["turn_deg"], far["cost_cm"]] == pytest.approx(expected)
    assert near["euclidean_cm"] == pytest.approx(100)
    assert far["euclidean_cm"] == pytest.approx(200)
    assert result["selected_candidate_id"] == "far"
    assert result["selected_cost_cm"] <= .9 * near["cost_cm"]
    assert sum(leg["distance_cm"] for leg in far["path"]) == pytest.approx(expected[3])
    assert near["projection"]["progress_cm"] == pytest.approx(case.get("near_s", 10))
    assert far["projection"]["progress_cm"] == pytest.approx(case.get("far_s", 20))


def single_road(one_way=False):
    return ([{"obj_id": "t", "x": 0, "z": .7}],
            {"edges": [edge("road", "A", "B", 100, one_way)]},
            {"roadId": "road", "roadProgressCm": 20, "onRoad": True},
            {"rightCm": 0, "forwardCm": 20, "headingDeg": 0},
            {"roads": {"road": [{"s": 0, "x": 0, "z": 0}, {"s": 100, "x": 0, "z": 1}]},
             "intervals": {"road": [[0, 100]]}}, .5)


def test_same_road_uses_partial_distance_not_node_detour():
    result = select_target(*single_road())
    assert result["selected_path_distance_cm"] == pytest.approx(50)
    assert result["candidates"][0]["path"][0]["kind"] == "same_road_partial"


def test_oneway_behind_target_unreachable_then_return_loop():
    args = list(single_road(True)); args[0][0]["z"] = .1
    result = select_target(*args)
    assert result["selected_candidate_id"] is None
    assert result["candidates"][0]["status"] == "unreachable"
    args[1]["edges"].append(edge("return", "B", "A", 150, True))
    result = select_target(*args)
    assert result["selected_path_distance_cm"] == pytest.approx(80 + 150 + 10)


def test_oneway_from_node_can_exit_other_edge_without_reverse_travel():
    args = list(single_road(True)); args[2]["roadProgressCm"] = 0; args[3]["forwardCm"] = 0
    args[0] = [{"obj_id": "t", "x": 1, "z": 0}]
    args[1]["edges"].append(edge("other", "A", "C", 100, True))
    args[4]["roads"]["other"] = [{"s": 0, "x": 0, "z": 0}, {"s": 100, "x": 1, "z": 0}]
    args[4]["intervals"]["other"] = [[0, 100]]
    assert select_target(*args)["selected_path_distance_cm"] == pytest.approx(100)


def test_unmeasured_gap_is_unknown_not_interpolated():
    args = list(single_road()); args[4]["intervals"]["road"] = [[0, 20], [80, 100]]
    result = select_target(*args)
    assert result["status"] == "unknown"
    assert result["candidates"][0]["reason"] == "no_measured_traversed_road_segment"


def test_touching_recorded_intervals_form_covered_segment():
    args = list(single_road()); args[4]["intervals"]["road"] = [[0, 30], [30, 60], [60, 100]]
    assert select_target(*args)["selected_path_distance_cm"] == pytest.approx(50)


def test_unmeasured_extension_not_replaced_with_clamped_midroad_point():
    args = list(single_road()); args[4]["roads"]["road"][1] = {"s": 40, "x": 0, "z": .4}
    args[4]["intervals"]["road"] = [[0, 40]]
    r = select_target(*args)
    assert r["candidates"][0]["reason"] == "nearest_measured_boundary_requires_unseen_geometry"
    assert r["candidates"][0]["cost_cm"] is None


def test_missing_geometry_stays_unknown_and_json_safe():
    args = list(single_road()); args[4] = {}
    r = select_target(*args)
    assert r["selected_candidate_id"] is None
    assert r["geometry_coverage"]["global_nearest_road_status"] == "unknown"
    json.dumps(r, allow_nan=False)


@pytest.mark.parametrize("k", [None, -1, math.nan, math.inf, True])
def test_measured_k_required_no_guessed_fallback(k):
    args = list(single_road()); args[-1] = k
    result = select_target(*args)
    assert result["reason"] == "measured_turn_cost_k_unavailable_or_invalid"
    assert result["selected_candidate_id"] is None
    json.dumps(result, allow_nan=False)


def test_no_default_k_in_signature():
    assert inspect.signature(select_target).parameters["k"].default is inspect.Parameter.empty
    with pytest.raises(TypeError):
        select_target(*single_road()[:-1])


def test_no_input_mutation_and_confidence_not_used_as_cost():
    args = inputs_for_case(SYNTHETIC_CASES[0]); before = copy.deepcopy(args)
    result = select_target(*args)
    assert args == before
    assert result["selected_candidate_id"] == "far"
    json.dumps(result, allow_nan=False)


def test_ties_deterministic_under_candidate_permutation():
    args = list(single_road());args[0] = [{"obj_id": "z", "x": 0, "z": .7}, {"obj_id": "a", "x": 0, "z": .7}]
    assert select_target(*args)["selected_candidate_id"] == "a"
    args[0].reverse()
    assert select_target(*args)["selected_candidate_id"] == "a"


def test_invalid_graph_and_offroad_current_are_explicit_unknown():
    args = list(single_road()); args[1]["edges"][0]["lengthCm"] = -100
    assert select_target(*args)["reason"] == "public_graph_or_current_road_invalid"
    args = list(single_road()); args[2]["onRoad"] = False
    assert select_target(*args)["reason"] == "public_graph_or_current_road_invalid"


def test_zero_length_cycle_terminates():
    args = list(single_road());args[1]["edges"].extend([edge("zero1", "A", "C", 0), edge("zero2", "C", "A", 0)])
    assert select_target(*args)["selected_path_distance_cm"] == pytest.approx(50)


def test_complete_source_after_actual_platform_async_transform():
    """Catches async method/alias/lambda mistakes using actual shipped transformer."""
    path = Path(__file__).resolve().parents[1] / "target_selection.py"
    source = path.read_text();tree = ast.parse(source)
    assert not any(isinstance(n, ast.ClassDef) for n in ast.walk(tree))
    names = {n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)}
    platform = Path(os.environ.get("GUANGYANG_PLATFORM_ROOT", "/Users/ken/Desktop/robot_competition-main/projects/car-python"))
    worker = (platform / "python-worker.js").read_text()
    transformer = worker[worker.index("class AsyncRobotTransformer("):worker.index("student_run_target =")]
    ns = {"ast": ast};exec(transformer, ns)
    transformed = ns["AsyncRobotTransformer"](names).visit(tree)
    ast.fix_missing_locations(transformed);runtime = {};exec(compile(transformed, str(path), "exec"), runtime)
    result = asyncio.run(runtime["select_target"](*inputs_for_case(SYNTHETIC_CASES[5])))
    assert result["selected_candidate_id"] == "far"
    assert result["selected_cost_cm"] == pytest.approx(265)
